### ISSUE TITLE
time series are shown in same color when the same variable

### ISSUE THREAD

**Issue by cpaulik** [TUW-GEO/ncweb#10]
![image](https://cloud.githubusercontent.com/assets/380927/4701693/b47e48c2-585b-11e4-85f3-d1295a60d0cf.png)

Both variables are sm and are shown in blue. Maybe we can name the time series variables no just like the variable is named in the netCDF file but prefix the name with the filename or dataset name

**Comment by poechtma** [comment]
Solved with Map Identifier in Labels (MapA: sm, MapB: sm)

in 8ceb9b5f23bd40ef745e681774315d00bbcf1707
