### ISSUE TITLE
Show loading time series overlay

### ISSUE THREAD

**Issue by cpaulik** [TUW-GEO/ncweb#5]
to give the user feedback that something is happening. Because it takes several seconds to generate the time series for large files.

e.g. spinning disk gif
![loading](https://cloud.githubusercontent.com/assets/380927/4539708/d281307a-4dff-11e4-9f58-6d253a6f6722.gif)

**Comment by poechtma** [comment]
Added loading icon as overlay in a00126584543a03ab77e8b6debd55965138bfed9
