### ISSUE TITLE
Zooming out on time series changes map timestamp

### ISSUE THREAD

**Issue by cpaulik** [TUW-GEO/ncweb#7]
Zooming out uses double click - might be a good idea to switch changing the timestamp to CTRL-Click like in the ASCAT dataviewer?

**Comment by poechtma** [comment]
Change date with ControlClick, Zoom out with DoubleClick

So there's no event on single click anymore

Changed in f10f1d34bbd3376c2e916aa9440df3dd5d2b06dd
